plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'net.darkhax.curseforgegradle' version '1.0.14'
    id 'com.modrinth.minotaur' version '2.+'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip")
    }

    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation("net.blay09.mods:balm-fabric:${balm_version}+${minecraft_version}") {
        exclude(group: 'net.blay09.mods', module: 'shared-bridge')
    }

    // Dependencies
    modImplementation "com.terraformersmc:modmenu:${modmenu_version}"
    modRuntimeOnly "me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}"
    modRuntimeOnly "maven.modrinth:yeetus-experimentus:${yeetus_experimentus_version}-fabric"

    // Dev dependencies
    modRuntimeOnly "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"

    implementation 'com.google.code.findbugs:jsr305:3.0.1'
    implementation project(":common")
}

loom {
    if (project(":common").file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath.set(project(":common").file("src/main/resources/${mod_id}.accesswidener"))
    }

//    mixin {
//        defaultRefmapName.set("${mod_id}.refmap.json")
//    }

    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }

        data {
            inherit client
            setConfigName("Fabric Data")
            ideConfigGenerated(true)
            runDir("build/datagen")

            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${project(":common").file("src/generated/resources")}"
            vmArg "-Dfabric-api.datagen.modid=${mod_id}"
        }

        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}

task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    dependsOn(build)
    description = 'Publishes the Fabric build to CurseForge'
    group = 'publishing'

    apiToken = findProperty('curseforge_token') ?: System.getenv('CURSEFORGE_TOKEN') ?: 'none'

    def mainFile = upload(curseforge_project_id, file("${project.buildDir}/libs/${mod_id}-${project.name}-${mod_version}-${minecraft_version}.jar"))
    mainFile.changelog = rootProject.file("changelogs/${mod_version}.md").text
    mainFile.releaseType = release_type
    mainFile.addGameVersion(minecraft_version)
    mainFile.addModLoader('Fabric')

    mainFile.addRequirement('fabric-api')
    mainFile.addRequirement('balm')
    mainFile.addRequirement('cloth-config')
    mainFile.addRequirement('yeetusexperimentus')
}

modrinth {
    token = findProperty('modrinth_token') ?: System.getenv('MODRINTH_TOKEN') ?: 'none'

    projectId = modrinth_project_id
    versionType = release_type
    versionNumber = mod_version + '+fabric-' + minecraft_version
    changelog = rootProject.file("changelogs/${mod_version}.md").text
    uploadFile = remapJar
    gameVersions = [minecraft_version]
    loaders = ['fabric']

    dependencies {
        required.project 'fabric-api'
        required.project 'balm'
        required.project 'cloth-config'
        required.project 'yeetus-experimentus'
    }
}

tasks.modrinth.dependsOn(build)
