plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
    id 'net.darkhax.curseforgegradle' version '1.0.14'
    id 'com.modrinth.minotaur' version '2.+'
}

//mixin {
//    add(sourceSets.main, "${mod_id}.refmap.json")
//
//    config("${mod_id}.mixins.json")
//    config("${mod_id}.forge.mixins.json")
//}

dependencies {
    modImplementation "net.blay09.mods:balm-common:${balm_version}+${minecraft_version}"
    modImplementation ("net.blay09.mods:balm-forge:${balm_version}+${minecraft_version}") {
        exclude(group: 'net.blay09.mods', module: 'shared-bridge')
    }

    // Dependencies
    modImplementation "me.shedaniel.cloth:cloth-config-forge:${cloth_config_version}"
    modRuntimeOnly "maven.modrinth:yeetus-experimentus:${yeetus_experimentus_version}-forge"

    // Dev dependencies
    modRuntimeOnly "mezz.jei:jei-${minecraft_version}-forge:${jei_version}"

    annotationProcessor 'org.spongepowered:mixin:0.8.5-SNAPSHOT:processor'
    compileOnly project(":common")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_version
    }

    runs {
        client {
            client()
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
        "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}

task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    dependsOn(build)
    description = 'Publishes the Forge build to CurseForge'
    group = 'publishing'

    apiToken = findProperty('curseforge_token') ?: System.getenv('CURSEFORGE_TOKEN') ?: 'none'

    def mainFile = upload(curseforge_project_id, file("${project.buildDir}/libs/${mod_id}-${project.name}-${mod_version}-${minecraft_version}.jar"))
    mainFile.changelog = rootProject.file("changelogs/${mod_version}.md").text
    mainFile.releaseType = release_type
    mainFile.addGameVersion(minecraft_version)
    mainFile.addModLoader('Forge')

    mainFile.addRequirement('balm')
    mainFile.addRequirement('cloth-config')
    mainFile.addRequirement('yeetusexperimentus')
}

modrinth {
    token = findProperty('modrinth_token') ?: System.getenv('MODRINTH_TOKEN') ?: 'none'

    projectId = modrinth_project_id
    versionType = release_type
    versionNumber = mod_version + '+forge-' + minecraft_version
    changelog = rootProject.file("changelogs/${mod_version}.md").text
    uploadFile = reobfJar
    gameVersions = [minecraft_version]
    loaders = ['forge']

    dependencies {
        required.project 'balm'
        required.project 'cloth-config'
        required.project 'yeetus-experimentus'
    }
}

tasks.modrinth.dependsOn(build)
